# encoding: utf-8

require 'rubygems'
<%= render_template 'bundler_setup.erb' %>
require 'rake'
<% if should_use_semver %>
require 'semver'

def s_version
  SemVer.find.format "%M.%m.%p%s"
end
<% end %>

<%= render_template 'juwelier_tasks.erb' %>

<%= render_template 'other_tasks.erb' %>
